pipeline:
  name: dfgretre
  identifier: dfgretre
  tags: {}
  projectIdentifier: RishiTest
  orgIdentifier: default
  stages:
    - stage:
        name: hf
        identifier: hf
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: <+input>
        tags: {}
