pipeline:
  name: dsfwefw
  identifier: dsfwefw
  tags: {}
  template:
    templateRef: fsdfewe
    versionLabel: ew
    templateInputs:
      stages:
        - stage:
            identifier: test12121
            template:
              templateInputs:
                type: Deployment
                spec:
                  service:
                    serviceInputs:
                      serviceDefinition:
                        type: Kubernetes
                        spec:
                          variables:
                            - name: var1
                              type: String
                              default: ef
                              value: <+input>
                            - name: var2
                              type: String
                              value: <+input>
                            - name: var3
                              type: String
                              value: <+input>
  projectIdentifier: fdsf
  orgIdentifier: default
