pipeline:
  name: "pipelineGitXUtk"
  identifier: "pipelineGitXUtk"
  template:
    templateRef: "pip1"
    versionLabel: "1"
    templateInputs:
      stages:
      - stage:
          identifier: "dgfd"
          template:
            templateInputs:
              type: "Approval"
              spec:
                execution:
                  steps:
                  - step:
                      identifier: "fg"
                      template:
                        templateInputs:
                          type: "ShellScript"
                          timeout: "<+input>"
  tags: {}
  projectIdentifier: "Default"
  orgIdentifier: "default"
