pipeline:
  name: remoteparent
  identifier: remoteparent
  projectIdentifier: fdsf
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: fsd
        identifier: fsd
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: remoteChild
          project: fdsf
