pipeline:
  name: tertretrefby
  identifier: tertretrefby
  tags: {}
  projectIdentifier: cxsa
  orgIdentifier: ljik
  stages:
    - stage:
        name: tyr
        identifier: tyr
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: ryt
                  identifier: ryt
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
