pipeline:
  name: test_pipeline
  identifier: test_pipeline
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ttr
        identifier: ttr
        tags: {}
        template:
          templateRef: stageTemplate2
          versionLabel: "1"
          templateInputs:
            type: Custom
            spec:
              execution:
                steps:
                  - step:
                      identifier: Wait_1
                      type: Wait
                      spec:
                        duration: <+input>
