pipeline:
  name: testImport
  identifier: testImport
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: eqweqew
        identifier: eqweqew
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10m
                  when:
                    stageStatus: Success
                    condition: "true"
        tags: {}
