pipeline:
  name: tretrwrerwq
  identifier: tretrwrerwq
  tags: {}
  template:
    templateRef: account.vdfwewrer
    versionLabel: ewqqwewq
    gitBranch: main-patch-e3-patch-3
  projectIdentifier: fdsf
  orgIdentifier: default
